### ISSUE TITLE
Panel snap issue with options `{circular: true, align: 'prev'}`

### ISSUE THREAD

**Issue by alexmnv** [naver/egjs-flicking#910]
With options `{circular: true, align: 'prev'}`, if you drag the panel almost all the way to the left, the panel returns to its original position on the right instead of scrolling to the left as expected. However, if you drag the panel just a little to the left, it scrolls to the left to the next panel as expected.  

You can reproduce the issue here: https://codesandbox.io/p/sandbox/mtqppv
Tested with **@egjs/flicking** version **4.12.0**.

**Comment by alexmnv** [comment]
https://github.com/user-attachments/assets/8e7a4be6-d977-4de1-b19d-b8826e72bbf6

<sup>Sorry for the video quality—I had to use my mobile phone because my screen recorder on Ubuntu 22.04 couldn't capture the cursor</sup>

**Comment by malangfox** [comment]
Hello @alexmnv.


We have released @egjs/flicking 4.12.1-beta.0 version that fixes the issue you left.
Try using the above version and leave comment if you encounter any issue or need any packages for framework.

**Comment by alexmnv** [comment]
Hello @malangfox.

https://github.com/user-attachments/assets/a40666ea-7c99-4d79-9f87-51667ba5123e

The issue is resolved when I drag a single panel, but it still occurs when I drag multiple panels

**Comment by malangfox** [comment]
Hello @alexmnv.

We have released @egjs/flicking 4.12.1-beta.4 version.
Can you try using the version above and leave a comment if you encounter any issues?

**Comment by alexmnv** [comment]
Hello @malangfox 
The issue described in this report seems to be completely fixed 👍 
But I noticed a new problem in `4.12.1-beta.4` that wasn’t present in `4.12.0`: multiple panels scroll simultaneously when I release the mouse button.

https://github.com/user-attachments/assets/35426397-9d0b-4b25-a42a-cade79159dc2
